#!/bin/sh

# Manual how to run nedded application at startup
# https://wiki.yoctoproject.org/wiki/FAQ:How_do_I_change_and_add_startup_scripts

. /etc/formfactor/config

SHOWCURSOR="no"

if [ "$HAVE_KEYBOARD" = "1" ]; then
    KEYBOARD_APPLET=""
else
    KEYBOARD_APPLET="keyboard"
fi

#matchbox-desktop &

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

START_APPLETS=showdesktop,windowselector
END_APPLETS=$KEYBOARD_APPLET,systray,startup-notify,notify
END_APPLETS=battery,$END_APPLETS # feature-acpi
END_APPLETS=battery,$END_APPLETS # feature-apm
END_APPLETS=clock,$END_APPLETS
END_APPLETS=openmoko-panel-gsm,$END_APPLETS # feature-phone

#matchbox-panel --start-applets $START_APPLETS --end-applets $END_APPLETS &

@APPNAME@ &

exec matchbox-window-manager -theme Sato -use_cursor $SHOWCURSOR $@
