[package]
name = "slint-gui"
version = "0.1.0"
authors = ["TEPO <tepotpoh@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
slint = { version = "1.3.2", default-features = false, features = ["std", "compat-1-2", @BACKEND_TYPE@, @RENDER_TYPE@] }
rumqttc = "0.23.0"
json = "0.12.4"
envconfig = "0.10.0"
chrono = "0.4"

[build-dependencies]
slint-build = "1.3.2"