[package]
name = "slint-gui"
version = "0.1.0"
authors = ["TEPO <tepotpoh@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
slint = "1.3.2"
rumqttc = "0.23.0"
json = "0.12.4"
envconfig = "0.10.0"
chrono = "0.4"

[build-dependencies]
slint-build = "1.3.2"