import { Switch } from "std-widgets.slint";
export component AnimationTestBox inherits Rectangle {
    rect := Rectangle {
        x:0;
        y: 5px;
        width: 40px;
        height: 40px;
        background: blue;
        animate x {
            duration: 500ms;
            easing: ease-in-out;
        }
        animate y {
            duration: 250ms;
            delay: 500ms;
            easing: ease-in;
        }
    }

    Switch {
        y: root.height/2;
        text: "Press to start animation";
        toggled => {
            if (self.checked) {
                rect.x = 0px;
                rect.y = 0px;
            } else {
                rect.x = parent.width - rect.width;
                rect.y = parent.height - rect.height;
            }
        }
    }
}