import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 1024px;
    height: 600px;
    background: #0b132b;
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
            color: green;
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
